-- DROPs
DROP TABLE IF EXISTS Personas CASCADE;
DROP TABLE IF EXISTS TelefonosPersona CASCADE;
DROP TABLE IF EXISTS CorreosPersona CASCADE;
DROP TABLE IF EXISTS Ubigeos CASCADE;
DROP TABLE IF EXISTS Empresas CASCADE;
DROP TABLE IF EXISTS TelefonosEmpresa CASCADE;
DROP TABLE IF EXISTS TiposUnidad CASCADE;
DROP TABLE IF EXISTS Vehiculos CASCADE;
DROP TABLE IF EXISTS EmpresasTransporte CASCADE;
DROP TABLE IF EXISTS Transportistas CASCADE;
DROP TABLE IF EXISTS GuiasRemision CASCADE;
DROP TABLE IF EXISTS ProgramacionesDespacho CASCADE;
DROP TABLE IF EXISTS RegistrosEntrega CASCADE;
DROP TABLE IF EXISTS OrdenesCarga CASCADE;
DROP TABLE IF EXISTS PedidosDespacho CASCADE;
DROP TABLE IF EXISTS TiposIncidencia CASCADE;
DROP TABLE IF EXISTS DetallesEntrega CASCADE;

DROP TABLE IF EXISTS Empleados CASCADE;
DROP TABLE IF EXISTS PedidosCliente CASCADE;
DROP TABLE IF EXISTS LotesProducto CASCADE;

-- ENUMs
DO $$ BEGIN
    DROP TYPE IF EXISTS estado_vehiculo_enum;
END $$;
CREATE TYPE estado_vehiculo_enum AS ENUM ('A', 'I');

DO $$ BEGIN
    DROP TYPE IF EXISTS tipo_cobertura_enum;
END $$;
CREATE TYPE tipo_cobertura_enum AS ENUM ('R', 'I', 'N');

DO $$ BEGIN
    DROP TYPE IF EXISTS tipo_servicio_enum;
END $$;
CREATE TYPE tipo_servicio_enum AS ENUM ('P', 'T');

DO $$ BEGIN
    DROP TYPE IF EXISTS motivo_traslado_enum;
END $$;
CREATE TYPE motivo_traslado_enum AS ENUM ('V', 'D');

DO $$ BEGIN
    DROP TYPE IF EXISTS estado_entrega_enum;
END $$;
CREATE TYPE estado_entrega_enum AS ENUM ('P', 'C', 'R');

DO $$ BEGIN
    DROP TYPE IF EXISTS estado_orden_carga_enum;
END $$;
CREATE TYPE estado_orden_carga_enum AS ENUM ('SP', 'PL', 'TR', 'IN', 'FN');

DO $$ BEGIN
    DROP TYPE IF EXISTS motivo_despacho_enum;
END $$;
CREATE TYPE motivo_despacho_enum AS ENUM ('E', 'R');

CREATE TABLE Empleados (
    ID_EMPLEADO SERIAL PRIMARY KEY
);

CREATE TABLE PedidosCliente (
    ID_PEDIDO_CLIENTE SERIAL PRIMARY KEY
);

CREATE TABLE LotesProducto (
    ID_LOTE_PRODUCTO SERIAL PRIMARY KEY
);


-- Tablas generales

CREATE TABLE Personas (
    ID_PERSONA SERIAL PRIMARY KEY,
    DNI CHAR(8) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    AP_PATERNO VARCHAR(50) NOT NULL,
    AP_MATERNO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100),
    FECHA_NAC DATE
);

CREATE TABLE TelefonosPersona (
    ID_PERSONA INT NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    PRIMARY KEY (ID_PERSONA, TELEFONO),
    FOREIGN KEY (ID_PERSONA) REFERENCES Personas(ID_PERSONA)
);

CREATE TABLE CorreosPersona (
    ID_PERSONA INT NOT NULL,
    CORREO VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID_PERSONA, CORREO),
    FOREIGN KEY (ID_PERSONA) REFERENCES Personas(ID_PERSONA)
);

CREATE TABLE Ubigeos (
    ID_UBIGEO CHAR(6) PRIMARY KEY,
    DEPARTAMENTO VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL,
    DISTRITO VARCHAR(50) NOT NULL
);

CREATE TABLE Empresas (
    ID_EMPRESA SERIAL PRIMARY KEY,
    CODIGO_RUC VARCHAR(11) NOT NULL UNIQUE,
    RAZON_SOCIAL VARCHAR(80) NOT NULL,
    NOMBRE_COMERCIAL VARCHAR(80),
    DIRECCION VARCHAR(150),
    UBIGEO_DIRECCION CHAR(6),
    FOREIGN KEY (UBIGEO_DIRECCION) REFERENCES Ubigeos(ID_UBIGEO)
);

CREATE TABLE TelefonosEmpresa (
    ID_EMPRESA INT NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    PRIMARY KEY (ID_EMPRESA, TELEFONO),
    FOREIGN KEY (ID_EMPRESA) REFERENCES Empresas(ID_EMPRESA)
);


CREATE TABLE TipoUnidad (
    CODIGO CHAR(4) PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);

CREATE TABLE TiposIncidencia (
    CODIGO CHAR(2) PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE Vehiculos (
    ID_VEHICULO SERIAL PRIMARY KEY,
    NUM_PLACA CHAR(10) NOT NULL UNIQUE,
    TIPO_UNIDAD CHAR(4) NOT NULL,
    ESTADO estado_vehiculo_enum NOT NULL,
    CAPAC_PESO NUMERIC(3) CHECK (CAPAC_PESO > 0),
    CAPAC_EMP NUMERIC(3) CHECK (CAPAC_EMP > 0),
    FOREIGN KEY (TIPO_UNIDAD) REFERENCES Tipo_Unidad(CODIGO)
);

DO $$ BEGIN
    DROP TYPE IF EXISTS tipo_cobertura_enum;
END $$;

CREATE TYPE tipo_cobertura_enum AS ENUM ('R', 'I', 'N');

CREATE TABLE EmpresasTransporte (
    ID_EMPRESA INT PRIMARY KEY,
    TIPO_COBERTURA tipo_cobertura_enum NOT NULL,
    DESCRIPCION VARCHAR(50),
    FOREIGN KEY (ID_EMPRESA) REFERENCES Empresas(ID_EMPRESA)
);

DO $$ BEGIN
    DROP TYPE IF EXISTS tipo_servicio_enum;
END $$;

CREATE TYPE tipo_servicio_enum AS ENUM ('P', 'T');

CREATE TABLE Transportistas (
    ID_TRANSPORTISTA SERIAL PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NUM_LICENCIA CHAR(9) NOT NULL UNIQUE,
    TIPO_SERVICIO tipo_servicio_enum NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES Empresas(ID_EMPRESA)
);

CREATE TABLE ProgramacionesDespacho (
    ID_PROG_DESP SERIAL PRIMARY KEY,
    ID_TRANSPORTISTA INT NOT NULL,
    ID_VEHICULO INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    CODIGO CHAR(10) NOT NULL UNIQUE,
    FECHA_PROG_SALIDA DATE NOT NULL,
    HORA_PROG_SALIDA TIME NOT NULL,
    FECHA_PROGRAMACION DATE NOT NULL,
    FOREIGN KEY (ID_TRANSPORTISTA) REFERENCES Transportistas(ID_TRANSPORTISTA),
    FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculos(ID_VEHICULO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES Empleados(ID_EMPLEADO)
);

CREATE TABLE OrdenesCarga (
    ID_ORDEN_CARGA SERIAL PRIMARY KEY,
    ID_PROG_DESP INT NOT NULL,
    CODIGO VARCHAR(10) NOT NULL UNIQUE,
    FECHA_SALIDA DATE NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    ESTADO estado_orden_carga_enum NOT NULL,

    FOREIGN KEY (ID_PROG_DESP) REFERENCES Programaciones_despacho(ID_PROG_DESP)
);

CREATE TABLE PedidosDespacho (
    ID_PROG_DESP INT NOT NULL,
    ID_PEDIDO_CLIENTE INT NOT NULL,
    MOTIVO_DESPACHO motivo_despacho_enum NOT NULL,

    PRIMARY KEY (ID_PROG_DESP, ID_PEDIDO_CLIENTE),

    FOREIGN KEY (ID_PROG_DESP) REFERENCES Programaciones_despacho(ID_PROG_DESP),
    FOREIGN KEY (ID_PEDIDO_CLIENTE) REFERENCES Pedidos_cliente(ID_PEDIDO_CLIENTE)
);

CREATE TABLE RegistrosEntrega (
    ID_REG_ENT SERIAL PRIMARY KEY,
    ID_ORDEN_CARGA INT NOT NULL,
    ID_PEDIDO_CLIENTE INT NOT NULL,
    ESTADO_ENTREGA estado_entrega_enum NOT NULL,
    FECHA_ENTREGA DATE NOT NULL,
    HORA_ENTREGA TIME NOT NULL,

    FOREIGN KEY (ID_ORDEN_CARGA) REFERENCES Ordenes_carga(ID_ORDEN_CARGA),
    FOREIGN KEY (ID_PEDIDO_CLIENTE) REFERENCES Pedidos_cliente(ID_PEDIDO_CLIENTE)
);

CREATE TABLE GuiasRemision (
    ID_GUIA_REM SERIAL PRIMARY KEY,
    ID_REG_ENT INT NOT NULL,
    NUM_GUIA CHAR(13) NOT NULL UNIQUE,
    MOTIVO_TRASLADO motivo_traslado_enum NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    ORIGEN_DIRECCION VARCHAR(150) NOT NULL,
    UBIGEO_ORIGEN CHAR(6) NOT NULL,
    DESTINO_DIRECCION VARCHAR(150) NOT NULL,
    UBIGEO_DESTINO CHAR(6) NOT NULL,
    FOREIGN KEY (ID_REG_ENT) REFERENCES Registros_entrega(ID_REG_ENT),
    FOREIGN KEY (UBIGEO_ORIGEN) REFERENCES Ubigeos(ID_UBIGEO),
    FOREIGN KEY (UBIGEO_DESTINO) REFERENCES Ubigeos(ID_UBIGEO)
);

CREATE TABLE DetallesEntrega (
    ID_REG_ENT INT NOT NULL,
    ID_LOTE_PRODUCTO INT NOT NULL,
    CANT_ENTREGADA NUMERIC(3) CHECK (CANT_ENTREGADA >= 0),
    CANT_OBSERVADA NUMERIC(3) CHECK (CANT_OBSERVADA >= 0),
    TIPO_INCIDENCIA CHAR(2),

    PRIMARY KEY (ID_REG_ENT, ID_LOTE_PRODUCTO),

    FOREIGN KEY (ID_REG_ENT) REFERENCES Registros_entrega(ID_REG_ENT),
    FOREIGN KEY (ID_LOTE_PRODUCTO) REFERENCES Lotes_producto(ID_LOTE_PRODUCTO),
    FOREIGN KEY (TIPO_INCIDENCIA) REFERENCES Tipos_Incidencia(CODIGO)
);